// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: panacea/datapool/v2/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the datapool module's genesis state.
type GenesisState struct {
	DataValidators             []DataValidator            `protobuf:"bytes,1,rep,name=data_validators,json=dataValidators,proto3" json:"data_validators"`
	NextPoolNumber             uint64                     `protobuf:"varint,2,opt,name=next_pool_number,json=nextPoolNumber,proto3" json:"next_pool_number,omitempty"`
	Pools                      []Pool                     `protobuf:"bytes,3,rep,name=pools,proto3" json:"pools"`
	Params                     Params                     `protobuf:"bytes,4,opt,name=params,proto3" json:"params"`
	DataPassRedeemReceipts     []DataPassRedeemReceipt    `protobuf:"bytes,5,rep,name=data_pass_redeem_receipts,json=dataPassRedeemReceipts,proto3" json:"data_pass_redeem_receipts"`
	InstantRevenueDistribution InstantRevenueDistribution `protobuf:"bytes,6,opt,name=instant_revenue_distribution,json=instantRevenueDistribution,proto3" json:"instant_revenue_distribution"`
	SalesHistories             []*SalesHistory            `protobuf:"bytes,7,rep,name=sales_histories,json=salesHistories,proto3" json:"sales_histories,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ac074515cc3a48, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetDataValidators() []DataValidator {
	if m != nil {
		return m.DataValidators
	}
	return nil
}

func (m *GenesisState) GetNextPoolNumber() uint64 {
	if m != nil {
		return m.NextPoolNumber
	}
	return 0
}

func (m *GenesisState) GetPools() []Pool {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetDataPassRedeemReceipts() []DataPassRedeemReceipt {
	if m != nil {
		return m.DataPassRedeemReceipts
	}
	return nil
}

func (m *GenesisState) GetInstantRevenueDistribution() InstantRevenueDistribution {
	if m != nil {
		return m.InstantRevenueDistribution
	}
	return InstantRevenueDistribution{}
}

func (m *GenesisState) GetSalesHistories() []*SalesHistory {
	if m != nil {
		return m.SalesHistories
	}
	return nil
}

// Params define parameters of datapool module
type Params struct {
	DataPoolCommissionRate     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=data_pool_commission_rate,json=dataPoolCommissionRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"data_pool_commission_rate" yaml:"data_pool_commission_rate"`
	DataPoolCodeId             uint64                                 `protobuf:"varint,2,opt,name=data_pool_code_id,json=dataPoolCodeId,proto3" json:"data_pool_code_id,omitempty"`
	DataPoolNftContractAddress string                                 `protobuf:"bytes,3,opt,name=data_pool_nft_contract_address,json=dataPoolNftContractAddress,proto3" json:"data_pool_nft_contract_address,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ac074515cc3a48, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDataPoolCodeId() uint64 {
	if m != nil {
		return m.DataPoolCodeId
	}
	return 0
}

func (m *Params) GetDataPoolNftContractAddress() string {
	if m != nil {
		return m.DataPoolNftContractAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "panacea.datapool.v2.GenesisState")
	proto.RegisterType((*Params)(nil), "panacea.datapool.v2.Params")
}

func init() { proto.RegisterFile("panacea/datapool/v2/genesis.proto", fileDescriptor_c5ac074515cc3a48) }

var fileDescriptor_c5ac074515cc3a48 = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x40, 0xe3, 0x36, 0x0d, 0xea, 0x16, 0xa5, 0x60, 0x10, 0x72, 0x03, 0x72, 0xd2, 0x1c, 0x90,
	0x41, 0xaa, 0x2d, 0x82, 0x38, 0xc0, 0x8d, 0x34, 0x12, 0x14, 0xa4, 0xaa, 0xb8, 0x12, 0x07, 0x2e,
	0xab, 0x8d, 0x77, 0x9a, 0xae, 0x6a, 0x7b, 0xad, 0x9d, 0x4d, 0x68, 0xbe, 0x80, 0x13, 0x12, 0x7f,
	0xc2, 0x6f, 0xf4, 0xd8, 0x23, 0xe2, 0x10, 0xa1, 0xe4, 0x0f, 0xf8, 0x02, 0xe4, 0xb5, 0x43, 0x72,
	0x70, 0x4e, 0xb6, 0x77, 0xde, 0x9b, 0xd9, 0x19, 0xef, 0x92, 0xc3, 0x8c, 0xa5, 0x2c, 0x02, 0x16,
	0x70, 0xa6, 0x59, 0x26, 0x65, 0x1c, 0x4c, 0x7a, 0xc1, 0x08, 0x52, 0x40, 0x81, 0x7e, 0xa6, 0xa4,
	0x96, 0xf6, 0x83, 0x12, 0xf1, 0x97, 0x88, 0x3f, 0xe9, 0xb5, 0x1e, 0x8e, 0xe4, 0x48, 0x9a, 0x78,
	0x90, 0xbf, 0x15, 0x68, 0xcb, 0xad, 0xca, 0x66, 0x14, 0x13, 0xef, 0xfe, 0xac, 0x93, 0xbb, 0xef,
	0x8a, 0xe4, 0xe7, 0x9a, 0x69, 0xb0, 0x3f, 0x91, 0xfd, 0x1c, 0xa5, 0x13, 0x16, 0x0b, 0xce, 0xb4,
	0x54, 0xe8, 0x58, 0x9d, 0x6d, 0x6f, 0xaf, 0xd7, 0xf5, 0x2b, 0xaa, 0xfa, 0x03, 0xa6, 0xd9, 0xe7,
	0x25, 0xda, 0xaf, 0xdf, 0xcc, 0xda, 0xb5, 0xb0, 0xc9, 0xd7, 0x17, 0xd1, 0xf6, 0xc8, 0xbd, 0x14,
	0xae, 0x35, 0xcd, 0x1d, 0x9a, 0x8e, 0x93, 0x21, 0x28, 0x67, 0xab, 0x63, 0x79, 0xf5, 0xb0, 0x99,
	0xaf, 0x9f, 0x49, 0x19, 0x9f, 0x9a, 0x55, 0xfb, 0x15, 0xd9, 0xc9, 0x21, 0x74, 0xb6, 0x4d, 0xc9,
	0x83, 0xca, 0x92, 0x39, 0x5f, 0x56, 0x2a, 0x68, 0xfb, 0x35, 0x69, 0x64, 0x4c, 0xb1, 0x04, 0x9d,
	0x7a, 0xc7, 0xf2, 0xf6, 0x7a, 0x8f, 0xab, 0x3d, 0x83, 0x94, 0x66, 0x29, 0xd8, 0x57, 0xe4, 0xc0,
	0xb4, 0x9b, 0x31, 0x44, 0xaa, 0x80, 0x03, 0x24, 0x54, 0x41, 0x04, 0x22, 0xd3, 0xe8, 0xec, 0x98,
	0x5d, 0x3c, 0xdf, 0xd8, 0xf8, 0x19, 0x43, 0x0c, 0x8d, 0x13, 0x16, 0x4a, 0x99, 0xfc, 0x11, 0xaf,
	0x0a, 0xa2, 0xfd, 0x95, 0x3c, 0x11, 0x29, 0x6a, 0x96, 0x6a, 0xaa, 0x60, 0x02, 0xe9, 0x18, 0x28,
	0x17, 0xa8, 0x95, 0x18, 0x8e, 0xb5, 0x90, 0xa9, 0xd3, 0x30, 0xbb, 0x0f, 0x2a, 0xeb, 0x9d, 0x14,
	0x62, 0x58, 0x78, 0x83, 0x35, 0xad, 0x2c, 0xda, 0x12, 0x1b, 0x09, 0xfb, 0x03, 0xd9, 0x47, 0x16,
	0x03, 0xd2, 0x4b, 0x81, 0x5a, 0x2a, 0x01, 0xe8, 0xdc, 0x31, 0xbd, 0x1d, 0x56, 0xd6, 0x3a, 0xcf,
	0xd9, 0xf7, 0x06, 0x9d, 0x86, 0x4d, 0x5c, 0x7d, 0x09, 0xc0, 0xee, 0xb7, 0x2d, 0xd2, 0x28, 0x46,
	0x69, 0x7f, 0xb7, 0x96, 0xd3, 0xcb, 0xff, 0x6c, 0x24, 0x93, 0x44, 0x20, 0x0a, 0x99, 0x52, 0xc5,
	0x34, 0x38, 0x56, 0xc7, 0xf2, 0x76, 0xfb, 0x61, 0xbe, 0xb9, 0xdf, 0xb3, 0xf6, 0xd3, 0x91, 0xd0,
	0x97, 0xe3, 0xa1, 0x1f, 0xc9, 0x24, 0x88, 0x24, 0x26, 0x12, 0xcb, 0xc7, 0x11, 0xf2, 0xab, 0x40,
	0x4f, 0x33, 0x40, 0x7f, 0x00, 0xd1, 0xdf, 0x59, 0xbb, 0x33, 0x65, 0x49, 0xfc, 0xa6, 0xbb, 0x31,
	0x71, 0xb7, 0x9c, 0xaf, 0x94, 0xf1, 0xf1, 0xff, 0x48, 0x98, 0x9f, 0xdd, 0x67, 0xe4, 0xfe, 0xba,
	0xc5, 0x81, 0x0a, 0xbe, 0x3c, 0x69, 0x2b, 0x85, 0xc3, 0x09, 0xb7, 0xfb, 0xc4, 0x5d, 0xa1, 0xe9,
	0x85, 0xa6, 0x91, 0x4c, 0xb5, 0x62, 0x91, 0xa6, 0x8c, 0x73, 0x05, 0x98, 0x1f, 0x41, 0xcb, 0xdb,
	0x0d, 0x5b, 0x4b, 0xef, 0xf4, 0x42, 0x1f, 0x97, 0xc8, 0xdb, 0x82, 0xe8, 0x7f, 0xbc, 0x99, 0xbb,
	0xd6, 0xed, 0xdc, 0xb5, 0xfe, 0xcc, 0x5d, 0xeb, 0xc7, 0xc2, 0xad, 0xdd, 0x2e, 0xdc, 0xda, 0xaf,
	0x85, 0x5b, 0xfb, 0xf2, 0x62, 0xad, 0xd9, 0x04, 0xb8, 0x18, 0xc6, 0x32, 0x0a, 0xca, 0x49, 0x1f,
	0x45, 0x52, 0x41, 0x70, 0xbd, 0xba, 0x90, 0xa6, 0xf7, 0x61, 0xc3, 0xdc, 0xc7, 0x97, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xf1, 0xe8, 0xd8, 0x96, 0xff, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SalesHistories) > 0 {
		for iNdEx := len(m.SalesHistories) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SalesHistories[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	{
		size, err := m.InstantRevenueDistribution.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.DataPassRedeemReceipts) > 0 {
		for iNdEx := len(m.DataPassRedeemReceipts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DataPassRedeemReceipts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Pools) > 0 {
		for iNdEx := len(m.Pools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.NextPoolNumber != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextPoolNumber))
		i--
		dAtA[i] = 0x10
	}
	if len(m.DataValidators) > 0 {
		for iNdEx := len(m.DataValidators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DataValidators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DataPoolNftContractAddress) > 0 {
		i -= len(m.DataPoolNftContractAddress)
		copy(dAtA[i:], m.DataPoolNftContractAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.DataPoolNftContractAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.DataPoolCodeId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DataPoolCodeId))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.DataPoolCommissionRate.Size()
		i -= size
		if _, err := m.DataPoolCommissionRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DataValidators) > 0 {
		for _, e := range m.DataValidators {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextPoolNumber != 0 {
		n += 1 + sovGenesis(uint64(m.NextPoolNumber))
	}
	if len(m.Pools) > 0 {
		for _, e := range m.Pools {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.DataPassRedeemReceipts) > 0 {
		for _, e := range m.DataPassRedeemReceipts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.InstantRevenueDistribution.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.SalesHistories) > 0 {
		for _, e := range m.SalesHistories {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DataPoolCommissionRate.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.DataPoolCodeId != 0 {
		n += 1 + sovGenesis(uint64(m.DataPoolCodeId))
	}
	l = len(m.DataPoolNftContractAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataValidators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataValidators = append(m.DataValidators, DataValidator{})
			if err := m.DataValidators[len(m.DataValidators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPoolNumber", wireType)
			}
			m.NextPoolNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPoolNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pools = append(m.Pools, Pool{})
			if err := m.Pools[len(m.Pools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPassRedeemReceipts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataPassRedeemReceipts = append(m.DataPassRedeemReceipts, DataPassRedeemReceipt{})
			if err := m.DataPassRedeemReceipts[len(m.DataPassRedeemReceipts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstantRevenueDistribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InstantRevenueDistribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SalesHistories", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SalesHistories = append(m.SalesHistories, &SalesHistory{})
			if err := m.SalesHistories[len(m.SalesHistories)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPoolCommissionRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DataPoolCommissionRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPoolCodeId", wireType)
			}
			m.DataPoolCodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DataPoolCodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataPoolNftContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataPoolNftContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
