FROM golang:1.26.5-trixie@sha256:8229e3b2cf7fc08878a86977547e3119c173681c3cc4a64c38cf0c6fe0b42fa8 AS build-env

ENV GOTOOLCHAIN=local

WORKDIR /src/panacea-core
COPY . ./
COPY --from=panacea_vendor . ./vendor

ARG PANACEA_VERSION=worktree
ARG PANACEA_COMMIT=unknown
ARG PANACEA_CMT_VERSION=unknown
RUN --network=none --mount=type=cache,target=/root/.cache/go-build \
    set -eu \
    && grep -Eq -- '-mod=(readonly|\$\(GO_BUILD_MOD\))' Makefile \
    && sed -i 's/-mod=readonly/-mod=$(GO_BUILD_MOD)/' Makefile \
    && grep -Fq -- '-mod=$(GO_BUILD_MOD)' Makefile \
    && sed -i \
        -e 's/^export VERSION :=.*/export VERSION ?= worktree/' \
        -e 's/^export COMMIT :=.*/export COMMIT ?= unknown/' \
        -e 's/^export CMTVERSION :=.*/export CMTVERSION ?= unknown/' \
        Makefile \
    && touch go.sum \
    && make build \
        LEDGER_ENABLED=false \
        GO_BUILD_MOD=vendor \
        VERSION="${PANACEA_VERSION}" \
        COMMIT="${PANACEA_COMMIT}" \
        CMTVERSION="${PANACEA_CMT_VERSION}"

FROM debian:trixie-slim@sha256:3a39a0592364683e6bab97937b72cad5a8fa6dcbbee90edb3bb48c7f8e94f258

COPY --from=build-env /src/panacea-core/build/panacead /usr/bin/panacead
RUN chmod 0755 /usr/bin/panacead

EXPOSE 26656 26657 1317 9090
