// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: panacea/oracle/v2alpha2/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the oracle module's genesis state.
type GenesisState struct {
	Oracles                             []Oracle                             `protobuf:"bytes,1,rep,name=oracles,proto3" json:"oracles"`
	OracleRegistrations                 []OracleRegistration                 `protobuf:"bytes,2,rep,name=oracle_registrations,json=oracleRegistrations,proto3" json:"oracle_registrations"`
	OracleRegistrationVotes             []OracleRegistrationVote             `protobuf:"bytes,3,rep,name=oracle_registration_votes,json=oracleRegistrationVotes,proto3" json:"oracle_registration_votes"`
	Params                              Params                               `protobuf:"bytes,4,opt,name=params,proto3" json:"params"`
	OracleUpgradeInfo                   *OracleUpgradeInfo                   `protobuf:"bytes,5,opt,name=oracle_upgrade_info,json=oracleUpgradeInfo,proto3" json:"oracle_upgrade_info,omitempty"`
	OracleRegistrationVoteQueueElements []OracleRegistrationVoteQueueElement `protobuf:"bytes,6,rep,name=oracle_registration_vote_queue_elements,json=oracleRegistrationVoteQueueElements,proto3" json:"oracle_registration_vote_queue_elements"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_138242ba6860f444, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetOracles() []Oracle {
	if m != nil {
		return m.Oracles
	}
	return nil
}

func (m *GenesisState) GetOracleRegistrations() []OracleRegistration {
	if m != nil {
		return m.OracleRegistrations
	}
	return nil
}

func (m *GenesisState) GetOracleRegistrationVotes() []OracleRegistrationVote {
	if m != nil {
		return m.OracleRegistrationVotes
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetOracleUpgradeInfo() *OracleUpgradeInfo {
	if m != nil {
		return m.OracleUpgradeInfo
	}
	return nil
}

func (m *GenesisState) GetOracleRegistrationVoteQueueElements() []OracleRegistrationVoteQueueElement {
	if m != nil {
		return m.OracleRegistrationVoteQueueElements
	}
	return nil
}

// Params defines the oracle module's params.
type Params struct {
	// A base64-encoded oracle public key which is paired with an oracle private key generated in SGX by the first oracle.
	// This key is used to encrypt data, so that the data can be decrypted and verified securely only in SGX
	OraclePublicKey string `protobuf:"bytes,1,opt,name=oracle_public_key,json=oraclePublicKey,proto3" json:"oracle_public_key,omitempty"`
	// A base64-encoded SGX remote report which contains an oracle public key.
	// Using this report, anyone can validate that the oracle key pair was generated in SGX.
	OraclePubKeyRemoteReport string `protobuf:"bytes,2,opt,name=oracle_pub_key_remote_report,json=oraclePubKeyRemoteReport,proto3" json:"oracle_pub_key_remote_report,omitempty"`
	// The unique ID of current version of oracle.
	UniqueId string `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	// Oracle commission rate on validating and delivering data
	OracleCommissionRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=oracle_commission_rate,json=oracleCommissionRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"oracle_commission_rate"`
	VoteParams           VoteParams                             `protobuf:"bytes,5,opt,name=vote_params,json=voteParams,proto3" json:"vote_params"`
	SlashParams          SlashParams                            `protobuf:"bytes,6,opt,name=slash_params,json=slashParams,proto3" json:"slash_params"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_138242ba6860f444, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetOraclePublicKey() string {
	if m != nil {
		return m.OraclePublicKey
	}
	return ""
}

func (m *Params) GetOraclePubKeyRemoteReport() string {
	if m != nil {
		return m.OraclePubKeyRemoteReport
	}
	return ""
}

func (m *Params) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *Params) GetVoteParams() VoteParams {
	if m != nil {
		return m.VoteParams
	}
	return VoteParams{}
}

func (m *Params) GetSlashParams() SlashParams {
	if m != nil {
		return m.SlashParams
	}
	return SlashParams{}
}

// Vote Params defines the params related to voting.
type VoteParams struct {
	VotingPeriod time.Duration                          `protobuf:"bytes,1,opt,name=voting_period,json=votingPeriod,proto3,stdduration" json:"voting_period" yaml:"voting_period"`
	JailPeriod   time.Duration                          `protobuf:"bytes,2,opt,name=jail_period,json=jailPeriod,proto3,stdduration" json:"jail_period" yaml:"jail_period"`
	Threshold    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=threshold,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"threshold"`
}

func (m *VoteParams) Reset()         { *m = VoteParams{} }
func (m *VoteParams) String() string { return proto.CompactTextString(m) }
func (*VoteParams) ProtoMessage()    {}
func (*VoteParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_138242ba6860f444, []int{2}
}
func (m *VoteParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VoteParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VoteParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VoteParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteParams.Merge(m, src)
}
func (m *VoteParams) XXX_Size() int {
	return m.Size()
}
func (m *VoteParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteParams.DiscardUnknown(m)
}

var xxx_messageInfo_VoteParams proto.InternalMessageInfo

func (m *VoteParams) GetVotingPeriod() time.Duration {
	if m != nil {
		return m.VotingPeriod
	}
	return 0
}

func (m *VoteParams) GetJailPeriod() time.Duration {
	if m != nil {
		return m.JailPeriod
	}
	return 0
}

// SlashParams defines the params related to slashing of oracle.
type SlashParams struct {
	SlashFractionDowntime github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=slash_fraction_downtime,json=slashFractionDowntime,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"slash_fraction_downtime"`
	SlashFractionForgery  github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=slash_fraction_forgery,json=slashFractionForgery,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"slash_fraction_forgery"`
}

func (m *SlashParams) Reset()         { *m = SlashParams{} }
func (m *SlashParams) String() string { return proto.CompactTextString(m) }
func (*SlashParams) ProtoMessage()    {}
func (*SlashParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_138242ba6860f444, []int{3}
}
func (m *SlashParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SlashParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SlashParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SlashParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlashParams.Merge(m, src)
}
func (m *SlashParams) XXX_Size() int {
	return m.Size()
}
func (m *SlashParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SlashParams.DiscardUnknown(m)
}

var xxx_messageInfo_SlashParams proto.InternalMessageInfo

// OracleRegistrationVoteQueueElement defines a oracle registration vote queue.
type OracleRegistrationVoteQueueElement struct {
	UniqueId      string    `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Address       []byte    `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	VotingEndTime time.Time `protobuf:"bytes,3,opt,name=voting_end_time,json=votingEndTime,proto3,stdtime" json:"voting_end_time" yaml:"voting_end_time"`
}

func (m *OracleRegistrationVoteQueueElement) Reset()         { *m = OracleRegistrationVoteQueueElement{} }
func (m *OracleRegistrationVoteQueueElement) String() string { return proto.CompactTextString(m) }
func (*OracleRegistrationVoteQueueElement) ProtoMessage()    {}
func (*OracleRegistrationVoteQueueElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_138242ba6860f444, []int{4}
}
func (m *OracleRegistrationVoteQueueElement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleRegistrationVoteQueueElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleRegistrationVoteQueueElement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleRegistrationVoteQueueElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleRegistrationVoteQueueElement.Merge(m, src)
}
func (m *OracleRegistrationVoteQueueElement) XXX_Size() int {
	return m.Size()
}
func (m *OracleRegistrationVoteQueueElement) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleRegistrationVoteQueueElement.DiscardUnknown(m)
}

var xxx_messageInfo_OracleRegistrationVoteQueueElement proto.InternalMessageInfo

func (m *OracleRegistrationVoteQueueElement) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *OracleRegistrationVoteQueueElement) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *OracleRegistrationVoteQueueElement) GetVotingEndTime() time.Time {
	if m != nil {
		return m.VotingEndTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "panacea.oracle.v2alpha2.GenesisState")
	proto.RegisterType((*Params)(nil), "panacea.oracle.v2alpha2.Params")
	proto.RegisterType((*VoteParams)(nil), "panacea.oracle.v2alpha2.VoteParams")
	proto.RegisterType((*SlashParams)(nil), "panacea.oracle.v2alpha2.SlashParams")
	proto.RegisterType((*OracleRegistrationVoteQueueElement)(nil), "panacea.oracle.v2alpha2.OracleRegistrationVoteQueueElement")
}

func init() {
	proto.RegisterFile("panacea/oracle/v2alpha2/genesis.proto", fileDescriptor_138242ba6860f444)
}

var fileDescriptor_138242ba6860f444 = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xcd, 0x6e, 0xeb, 0x44,
	0x14, 0xc7, 0xe3, 0xa4, 0xe4, 0x92, 0x49, 0xd0, 0x15, 0x43, 0xb9, 0xf5, 0x2d, 0xc8, 0x89, 0x7c,
	0x2f, 0x50, 0x15, 0xd5, 0x96, 0xc2, 0x0e, 0x04, 0x48, 0xa1, 0x2d, 0x2a, 0x2d, 0xa2, 0xb8, 0xc0,
	0xa2, 0x1b, 0x33, 0xb1, 0x27, 0x8e, 0xa9, 0xed, 0x71, 0x67, 0xc6, 0x81, 0xbc, 0x45, 0xc5, 0x86,
	0xbe, 0x0f, 0x9b, 0x2e, 0xbb, 0x44, 0x20, 0x0a, 0x6a, 0xdf, 0x80, 0x27, 0x40, 0xf3, 0xe1, 0xe6,
	0xa3, 0xcd, 0x8d, 0xb2, 0x4a, 0x7c, 0xe6, 0x7f, 0x7e, 0xe7, 0xcc, 0x39, 0x67, 0x66, 0xc0, 0x7b,
	0x39, 0xca, 0x50, 0x80, 0x91, 0x4b, 0x28, 0x0a, 0x12, 0xec, 0x8e, 0xba, 0x28, 0xc9, 0x87, 0xa8,
	0xeb, 0x46, 0x38, 0xc3, 0x2c, 0x66, 0x4e, 0x4e, 0x09, 0x27, 0x70, 0x43, 0xcb, 0x1c, 0x25, 0x73,
	0x4a, 0xd9, 0xe6, 0x7a, 0x44, 0x22, 0x22, 0x35, 0xae, 0xf8, 0xa7, 0xe4, 0x9b, 0x56, 0x44, 0x48,
	0x94, 0x60, 0x57, 0x7e, 0xf5, 0x8b, 0x81, 0x1b, 0x16, 0x14, 0xf1, 0x98, 0x64, 0x7a, 0xbd, 0x3d,
	0xbf, 0xce, 0xe3, 0x14, 0x33, 0x8e, 0xd2, 0x5c, 0x0b, 0x5e, 0x2e, 0x4a, 0x4b, 0xc7, 0x97, 0x2a,
	0xfb, 0xef, 0x35, 0xd0, 0xfa, 0x52, 0xe5, 0x79, 0xc2, 0x11, 0xc7, 0xf0, 0x73, 0xf0, 0x44, 0x09,
	0x98, 0x69, 0x74, 0x6a, 0x5b, 0xcd, 0x6e, 0xdb, 0x59, 0x90, 0xb8, 0xf3, 0x8d, 0xfc, 0xee, 0xad,
	0x5d, 0xdd, 0xb4, 0x2b, 0x5e, 0xe9, 0x05, 0x43, 0xb0, 0xae, 0xfe, 0xfa, 0x14, 0x47, 0x31, 0xe3,
	0x2a, 0x6b, 0x66, 0x56, 0x25, 0xed, 0xc3, 0x25, 0x34, 0x6f, 0xca, 0x47, 0x93, 0xdf, 0x22, 0x0f,
	0x56, 0x18, 0x3c, 0x07, 0xcf, 0x1f, 0x89, 0xe2, 0x8f, 0x08, 0xc7, 0xcc, 0xac, 0xc9, 0x50, 0xee,
	0x0a, 0xa1, 0x7e, 0x20, 0xbc, 0xdc, 0xc8, 0x06, 0x79, 0x74, 0x95, 0xc1, 0x4f, 0x41, 0x3d, 0x47,
	0x14, 0xa5, 0xcc, 0x5c, 0xeb, 0x18, 0xaf, 0x2c, 0xcc, 0xb1, 0x94, 0x69, 0x9e, 0x76, 0x82, 0xa7,
	0x40, 0x6f, 0xc4, 0x2f, 0xf2, 0x88, 0xa2, 0x10, 0xfb, 0x71, 0x36, 0x20, 0xe6, 0x6b, 0x92, 0xb5,
	0xbd, 0x24, 0xd7, 0xef, 0x95, 0xcb, 0x41, 0x36, 0x20, 0xde, 0x9b, 0x64, 0xde, 0x04, 0x7f, 0x33,
	0xc0, 0x07, 0x8b, 0xca, 0xe1, 0x9f, 0x17, 0xb8, 0xc0, 0x3e, 0x4e, 0x70, 0x8a, 0x33, 0xce, 0xcc,
	0xba, 0x2c, 0xce, 0x27, 0x2b, 0x16, 0xe7, 0x5b, 0x01, 0xd9, 0x53, 0x0c, 0xbd, 0xb1, 0x17, 0x64,
	0xa9, 0x92, 0xd9, 0xbf, 0xd6, 0x40, 0x5d, 0x95, 0x03, 0x6e, 0x03, 0x9d, 0xb9, 0x9f, 0x17, 0xfd,
	0x24, 0x0e, 0xfc, 0x33, 0x3c, 0x36, 0x8d, 0x8e, 0xb1, 0xd5, 0xf0, 0x9e, 0xaa, 0x85, 0x63, 0x69,
	0x3f, 0xc4, 0x63, 0xf8, 0x19, 0x78, 0x77, 0xa2, 0x15, 0x42, 0x9f, 0xe2, 0x54, 0x6c, 0x86, 0xe2,
	0x9c, 0x50, 0x6e, 0x56, 0xa5, 0x9b, 0x79, 0xef, 0x76, 0x88, 0xc7, 0x9e, 0x14, 0x78, 0x72, 0x1d,
	0xbe, 0x03, 0x1a, 0x45, 0x16, 0x9f, 0x17, 0xd8, 0x8f, 0x43, 0xb3, 0x26, 0xc5, 0xaf, 0x2b, 0xc3,
	0x41, 0x08, 0x43, 0xf0, 0x4c, 0xc3, 0x03, 0x92, 0xa6, 0x31, 0x63, 0xa2, 0x54, 0x14, 0x71, 0x2c,
	0x1b, 0xdb, 0xe8, 0x39, 0x62, 0x7b, 0x7f, 0xde, 0xb4, 0xdf, 0x8f, 0x62, 0x3e, 0x2c, 0xfa, 0x4e,
	0x40, 0x52, 0x37, 0x20, 0x2c, 0x25, 0x4c, 0xff, 0xec, 0xb0, 0xf0, 0xcc, 0xe5, 0xe3, 0x1c, 0x33,
	0x67, 0x17, 0x07, 0x9e, 0x9e, 0xf7, 0x2f, 0xee, 0x61, 0x9e, 0x38, 0x48, 0x5f, 0x81, 0xa6, 0x2c,
	0xbf, 0x9e, 0x19, 0xd5, 0xe7, 0x17, 0x0b, 0xcb, 0x2e, 0x4a, 0x37, 0x33, 0x37, 0x60, 0x74, 0x6f,
	0x81, 0x5f, 0x83, 0x16, 0x4b, 0x10, 0x1b, 0x96, 0xb0, 0xba, 0x84, 0xbd, 0x5c, 0x08, 0x3b, 0x11,
	0xe2, 0x19, 0x5a, 0x93, 0x4d, 0x4c, 0xf6, 0x65, 0x15, 0x80, 0x49, 0x3c, 0xf8, 0x23, 0x78, 0x63,
	0x44, 0x78, 0x9c, 0x45, 0x7e, 0x8e, 0x69, 0x4c, 0x42, 0xd9, 0x94, 0x66, 0xf7, 0xb9, 0xa3, 0xae,
	0x18, 0xa7, 0xbc, 0x62, 0x9c, 0x5d, 0x7d, 0x05, 0xf5, 0x3a, 0x82, 0xf9, 0xdf, 0x4d, 0x7b, 0x7d,
	0x8c, 0xd2, 0xe4, 0x63, 0x7b, 0xc6, 0xdb, 0xbe, 0xfc, 0xa7, 0x6d, 0x78, 0x2d, 0x65, 0x3b, 0x96,
	0x26, 0x78, 0x0a, 0x9a, 0x3f, 0xa1, 0x38, 0x29, 0xf9, 0xd5, 0x65, 0x7c, 0x4b, 0xf3, 0xa1, 0xe2,
	0x4f, 0xf9, 0x2a, 0x3a, 0x10, 0x16, 0xcd, 0x3e, 0x02, 0x0d, 0x3e, 0xa4, 0x98, 0x0d, 0x49, 0xa2,
	0x5b, 0xbd, 0x72, 0x03, 0x27, 0x00, 0xfb, 0x2f, 0x03, 0x34, 0xa7, 0xaa, 0x07, 0x07, 0x60, 0x43,
	0x55, 0x7e, 0x40, 0x51, 0x20, 0xcf, 0x54, 0x48, 0x7e, 0xce, 0xc4, 0x5d, 0xab, 0x46, 0x77, 0xe5,
	0x58, 0x6f, 0x4b, 0xdc, 0xbe, 0xa6, 0xed, 0x6a, 0x98, 0x98, 0xc9, 0xb9, 0x38, 0x03, 0x42, 0x23,
	0x4c, 0xc7, 0x6a, 0xd4, 0x57, 0x9f, 0xc9, 0x99, 0x30, 0xfb, 0x8a, 0x65, 0xff, 0x6e, 0x00, 0x7b,
	0xf9, 0xf9, 0x9e, 0x3d, 0x3d, 0xc6, 0xdc, 0xe9, 0x31, 0xc1, 0x13, 0x14, 0x86, 0x14, 0x33, 0x26,
	0x53, 0x6b, 0x79, 0xe5, 0x27, 0x1c, 0x80, 0xa7, 0x7a, 0x12, 0x70, 0x16, 0xfa, 0xb2, 0x46, 0x35,
	0xd9, 0xe9, 0xcd, 0x07, 0x9d, 0xfe, 0xae, 0x7c, 0xac, 0x7a, 0xb6, 0x6e, 0xf5, 0xb3, 0x99, 0x51,
	0x2a, 0x01, 0xf6, 0x85, 0x68, 0xb7, 0x1e, 0xcf, 0xbd, 0x2c, 0x14, 0x7e, 0xbd, 0xa3, 0xab, 0x5b,
	0xcb, 0xb8, 0xbe, 0xb5, 0x8c, 0x7f, 0x6f, 0x2d, 0xe3, 0xe2, 0xce, 0xaa, 0x5c, 0xdf, 0x59, 0x95,
	0x3f, 0xee, 0xac, 0xca, 0x69, 0x77, 0xaa, 0x3a, 0x29, 0x0e, 0xe3, 0x7e, 0x42, 0x02, 0x57, 0x1f,
	0x92, 0x9d, 0x80, 0x50, 0xf1, 0x0a, 0xba, 0xbf, 0x94, 0x2f, 0xa2, 0xac, 0x56, 0xbf, 0x2e, 0x93,
	0xfa, 0xe8, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xd6, 0x54, 0x89, 0xc7, 0x07, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OracleRegistrationVoteQueueElements) > 0 {
		for iNdEx := len(m.OracleRegistrationVoteQueueElements) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OracleRegistrationVoteQueueElements[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.OracleUpgradeInfo != nil {
		{
			size, err := m.OracleUpgradeInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.OracleRegistrationVotes) > 0 {
		for iNdEx := len(m.OracleRegistrationVotes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OracleRegistrationVotes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.OracleRegistrations) > 0 {
		for iNdEx := len(m.OracleRegistrations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OracleRegistrations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Oracles) > 0 {
		for iNdEx := len(m.Oracles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Oracles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SlashParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.VoteParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.OracleCommissionRate.Size()
		i -= size
		if _, err := m.OracleCommissionRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.UniqueId) > 0 {
		i -= len(m.UniqueId)
		copy(dAtA[i:], m.UniqueId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.UniqueId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OraclePubKeyRemoteReport) > 0 {
		i -= len(m.OraclePubKeyRemoteReport)
		copy(dAtA[i:], m.OraclePubKeyRemoteReport)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.OraclePubKeyRemoteReport)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OraclePublicKey) > 0 {
		i -= len(m.OraclePublicKey)
		copy(dAtA[i:], m.OraclePublicKey)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.OraclePublicKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VoteParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VoteParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VoteParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Threshold.Size()
		i -= size
		if _, err := m.Threshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	n5, err5 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.JailPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.JailPeriod):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintGenesis(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x12
	n6, err6 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.VotingPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.VotingPeriod):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintGenesis(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *SlashParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SlashParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SlashParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.SlashFractionForgery.Size()
		i -= size
		if _, err := m.SlashFractionForgery.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.SlashFractionDowntime.Size()
		i -= size
		if _, err := m.SlashFractionDowntime.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *OracleRegistrationVoteQueueElement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleRegistrationVoteQueueElement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleRegistrationVoteQueueElement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n7, err7 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.VotingEndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.VotingEndTime):])
	if err7 != nil {
		return 0, err7
	}
	i -= n7
	i = encodeVarintGenesis(dAtA, i, uint64(n7))
	i--
	dAtA[i] = 0x1a
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UniqueId) > 0 {
		i -= len(m.UniqueId)
		copy(dAtA[i:], m.UniqueId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.UniqueId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Oracles) > 0 {
		for _, e := range m.Oracles {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OracleRegistrations) > 0 {
		for _, e := range m.OracleRegistrations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OracleRegistrationVotes) > 0 {
		for _, e := range m.OracleRegistrationVotes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.OracleUpgradeInfo != nil {
		l = m.OracleUpgradeInfo.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.OracleRegistrationVoteQueueElements) > 0 {
		for _, e := range m.OracleRegistrationVoteQueueElements {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OraclePublicKey)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.OraclePubKeyRemoteReport)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.UniqueId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.OracleCommissionRate.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.VoteParams.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.SlashParams.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *VoteParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.VotingPeriod)
	n += 1 + l + sovGenesis(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.JailPeriod)
	n += 1 + l + sovGenesis(uint64(l))
	l = m.Threshold.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *SlashParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SlashFractionDowntime.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.SlashFractionForgery.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *OracleRegistrationVoteQueueElement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UniqueId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.VotingEndTime)
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Oracles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Oracles = append(m.Oracles, Oracle{})
			if err := m.Oracles[len(m.Oracles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleRegistrations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleRegistrations = append(m.OracleRegistrations, OracleRegistration{})
			if err := m.OracleRegistrations[len(m.OracleRegistrations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleRegistrationVotes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleRegistrationVotes = append(m.OracleRegistrationVotes, OracleRegistrationVote{})
			if err := m.OracleRegistrationVotes[len(m.OracleRegistrationVotes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleUpgradeInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OracleUpgradeInfo == nil {
				m.OracleUpgradeInfo = &OracleUpgradeInfo{}
			}
			if err := m.OracleUpgradeInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleRegistrationVoteQueueElements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleRegistrationVoteQueueElements = append(m.OracleRegistrationVoteQueueElements, OracleRegistrationVoteQueueElement{})
			if err := m.OracleRegistrationVoteQueueElements[len(m.OracleRegistrationVoteQueueElements)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OraclePublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OraclePublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OraclePubKeyRemoteReport", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OraclePubKeyRemoteReport = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniqueId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleCommissionRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OracleCommissionRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VoteParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VoteParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VoteParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.VotingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JailPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.JailPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Threshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SlashParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SlashParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SlashParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFractionDowntime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFractionDowntime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFractionForgery", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFractionForgery.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OracleRegistrationVoteQueueElement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleRegistrationVoteQueueElement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleRegistrationVoteQueueElement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniqueId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingEndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.VotingEndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
