// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: panacea/oracle/v2/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the oracle module's genesis state.
type GenesisState struct {
	Oracles             []Oracle             `protobuf:"bytes,1,rep,name=oracles,proto3" json:"oracles"`
	OracleRegistrations []OracleRegistration `protobuf:"bytes,2,rep,name=oracle_registrations,json=oracleRegistrations,proto3" json:"oracle_registrations"`
	OracleUpgrades      []OracleUpgrade      `protobuf:"bytes,3,rep,name=oracle_upgrades,json=oracleUpgrades,proto3" json:"oracle_upgrades"`
	OracleUpgradeInfo   *OracleUpgradeInfo   `protobuf:"bytes,4,opt,name=oracle_upgrade_info,json=oracleUpgradeInfo,proto3" json:"oracle_upgrade_info,omitempty"`
	Params              Params               `protobuf:"bytes,5,opt,name=params,proto3" json:"params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_321e5b447e46614a, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetOracles() []Oracle {
	if m != nil {
		return m.Oracles
	}
	return nil
}

func (m *GenesisState) GetOracleRegistrations() []OracleRegistration {
	if m != nil {
		return m.OracleRegistrations
	}
	return nil
}

func (m *GenesisState) GetOracleUpgrades() []OracleUpgrade {
	if m != nil {
		return m.OracleUpgrades
	}
	return nil
}

func (m *GenesisState) GetOracleUpgradeInfo() *OracleUpgradeInfo {
	if m != nil {
		return m.OracleUpgradeInfo
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// Params defines the oracle module's params.
type Params struct {
	// A base64-encoded oracle public key which is paired with an oracle private key generated in SGX by the first oracle.
	// This key is used to encrypt data, so that the data can be decrypted and verified securely only in SGX
	OraclePublicKey string `protobuf:"bytes,1,opt,name=oracle_public_key,json=oraclePublicKey,proto3" json:"oracle_public_key,omitempty"`
	// A base64-encoded SGX remote report which contains an oracle public key.
	// Using this report, anyone can validate that the oracle key pair was generated in SGX.
	OraclePubKeyRemoteReport string `protobuf:"bytes,2,opt,name=oracle_pub_key_remote_report,json=oraclePubKeyRemoteReport,proto3" json:"oracle_pub_key_remote_report,omitempty"`
	// The unique ID of current version of oracle.
	UniqueId string `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_321e5b447e46614a, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetOraclePublicKey() string {
	if m != nil {
		return m.OraclePublicKey
	}
	return ""
}

func (m *Params) GetOraclePubKeyRemoteReport() string {
	if m != nil {
		return m.OraclePubKeyRemoteReport
	}
	return ""
}

func (m *Params) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "panacea.oracle.v2.GenesisState")
	proto.RegisterType((*Params)(nil), "panacea.oracle.v2.Params")
}

func init() { proto.RegisterFile("panacea/oracle/v2/genesis.proto", fileDescriptor_321e5b447e46614a) }

var fileDescriptor_321e5b447e46614a = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xe3, 0x65, 0x14, 0xe6, 0x21, 0xd0, 0xbc, 0x1d, 0xcc, 0x40, 0x59, 0x34, 0x81, 0x54,
	0x21, 0x91, 0x48, 0xe1, 0x80, 0xb8, 0x70, 0xd8, 0x05, 0x4d, 0x43, 0xda, 0x14, 0xe0, 0xc2, 0x81,
	0xc8, 0x49, 0xdc, 0x60, 0xd1, 0xe4, 0x05, 0xdb, 0xa9, 0xc8, 0x47, 0xe0, 0x06, 0xdf, 0xaa, 0xc7,
	0x1e, 0x39, 0x21, 0xd4, 0x7e, 0x11, 0x54, 0xdb, 0x85, 0x42, 0xa9, 0x76, 0x7b, 0x7a, 0xff, 0xdf,
	0xfb, 0x25, 0x79, 0x79, 0xf8, 0xa4, 0x65, 0x0d, 0x2b, 0x38, 0x8b, 0x41, 0xb2, 0x62, 0xcc, 0xe3,
	0x49, 0x12, 0x57, 0xbc, 0xe1, 0x4a, 0xa8, 0xa8, 0x95, 0xa0, 0x81, 0x1c, 0x38, 0x20, 0xb2, 0x40,
	0x34, 0x49, 0x8e, 0x8f, 0x2a, 0xa8, 0xc0, 0xa4, 0xf1, 0xb2, 0xb2, 0xe0, 0x71, 0xb0, 0x69, 0x72,
	0x23, 0x26, 0x3f, 0xfd, 0xe2, 0xe3, 0xdb, 0x2f, 0xad, 0xfa, 0xb5, 0x66, 0x9a, 0x93, 0xe7, 0xf8,
	0xa6, 0x05, 0x14, 0x45, 0xa1, 0x3f, 0xdc, 0x4f, 0xee, 0x45, 0x1b, 0xcf, 0x8a, 0x2e, 0x4d, 0x75,
	0xb6, 0x3b, 0xfd, 0x71, 0xe2, 0xa5, 0x2b, 0x9e, 0xbc, 0xc7, 0x47, 0xb6, 0xcc, 0x24, 0xaf, 0x84,
	0xd2, 0x92, 0x69, 0x01, 0x8d, 0xa2, 0x3b, 0xc6, 0xf3, 0x68, 0xab, 0x27, 0x5d, 0xa3, 0x9d, 0xf3,
	0x10, 0x36, 0x12, 0x45, 0x2e, 0xf1, 0x5d, 0xe7, 0xef, 0xda, 0x4a, 0xb2, 0x92, 0x2b, 0xea, 0x1b,
	0x75, 0xb8, 0x55, 0xfd, 0xd6, 0x82, 0xce, 0x7a, 0x07, 0xd6, 0x9b, 0x8a, 0xbc, 0xc1, 0x87, 0x7f,
	0x0b, 0x33, 0xd1, 0x8c, 0x80, 0xee, 0x86, 0x68, 0xb8, 0x9f, 0x3c, 0xbc, 0x4e, 0x7a, 0xde, 0x8c,
	0x20, 0x3d, 0x80, 0x7f, 0x5b, 0xe4, 0x19, 0x1e, 0xb4, 0x4c, 0xb2, 0x5a, 0xd1, 0x1b, 0x46, 0xf4,
	0xbf, 0x05, 0x5e, 0x19, 0xc0, 0xbd, 0x96, 0xc3, 0x4f, 0xbf, 0x21, 0x3c, 0xb0, 0x01, 0x79, 0x8c,
	0x9d, 0x38, 0x6b, 0xbb, 0x7c, 0x2c, 0x8a, 0xec, 0x23, 0xef, 0x29, 0x0a, 0xd1, 0x70, 0x2f, 0x75,
	0x3b, 0xb8, 0x32, 0xfd, 0x0b, 0xde, 0x93, 0x17, 0xf8, 0xc1, 0x1f, 0x76, 0x09, 0x66, 0x92, 0xd7,
	0xa0, 0x97, 0x7f, 0xa1, 0x05, 0xa9, 0xe9, 0x8e, 0x19, 0xa3, 0xbf, 0xc7, 0x2e, 0x78, 0x9f, 0x1a,
	0x20, 0x35, 0x39, 0xb9, 0x8f, 0xf7, 0xba, 0x46, 0x7c, 0xea, 0x78, 0x26, 0x4a, 0xea, 0x1b, 0xf8,
	0x96, 0x6d, 0x9c, 0x97, 0x67, 0xaf, 0xa6, 0xf3, 0x00, 0xcd, 0xe6, 0x01, 0xfa, 0x39, 0x0f, 0xd0,
	0xd7, 0x45, 0xe0, 0xcd, 0x16, 0x81, 0xf7, 0x7d, 0x11, 0x78, 0xef, 0x92, 0x4a, 0xe8, 0x0f, 0x5d,
	0x1e, 0x15, 0x50, 0xc7, 0x35, 0x2f, 0x45, 0x3e, 0x86, 0x22, 0x76, 0x5f, 0xfa, 0xa4, 0x00, 0x69,
	0x6e, 0xed, 0xf3, 0xea, 0xee, 0x74, 0xdf, 0x72, 0x95, 0x0f, 0xcc, 0xd1, 0x3d, 0xfd, 0x15, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0x2b, 0x7d, 0xee, 0xe0, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.OracleUpgradeInfo != nil {
		{
			size, err := m.OracleUpgradeInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.OracleUpgrades) > 0 {
		for iNdEx := len(m.OracleUpgrades) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OracleUpgrades[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.OracleRegistrations) > 0 {
		for iNdEx := len(m.OracleRegistrations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OracleRegistrations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Oracles) > 0 {
		for iNdEx := len(m.Oracles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Oracles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UniqueId) > 0 {
		i -= len(m.UniqueId)
		copy(dAtA[i:], m.UniqueId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.UniqueId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OraclePubKeyRemoteReport) > 0 {
		i -= len(m.OraclePubKeyRemoteReport)
		copy(dAtA[i:], m.OraclePubKeyRemoteReport)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.OraclePubKeyRemoteReport)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OraclePublicKey) > 0 {
		i -= len(m.OraclePublicKey)
		copy(dAtA[i:], m.OraclePublicKey)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.OraclePublicKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Oracles) > 0 {
		for _, e := range m.Oracles {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OracleRegistrations) > 0 {
		for _, e := range m.OracleRegistrations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OracleUpgrades) > 0 {
		for _, e := range m.OracleUpgrades {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.OracleUpgradeInfo != nil {
		l = m.OracleUpgradeInfo.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OraclePublicKey)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.OraclePubKeyRemoteReport)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.UniqueId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Oracles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Oracles = append(m.Oracles, Oracle{})
			if err := m.Oracles[len(m.Oracles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleRegistrations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleRegistrations = append(m.OracleRegistrations, OracleRegistration{})
			if err := m.OracleRegistrations[len(m.OracleRegistrations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleUpgrades", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OracleUpgrades = append(m.OracleUpgrades, OracleUpgrade{})
			if err := m.OracleUpgrades[len(m.OracleUpgrades)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleUpgradeInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OracleUpgradeInfo == nil {
				m.OracleUpgradeInfo = &OracleUpgradeInfo{}
			}
			if err := m.OracleUpgradeInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OraclePublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OraclePublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OraclePubKeyRemoteReport", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OraclePubKeyRemoteReport = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniqueId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
