name: ci

on:
  push:
    branches:    # only for pushes on master
    - master
  pull_request:  # for all PRs regardless of its base branch

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run protoc
      run: make proto-gen

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.30

    - name: Publish coverage.html as an artifact
      uses: actions/upload-artifact@master
      with:
        name: coverage
        path: artifacts/coverage.html
