name: ci

on:
  push:
    branches:    # only for pushes on master
    - develop
    - main
    - release/v*.*.*
  pull_request:  # for all PRs regardless of its base branch

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build (+ generating proto and docs)
      run: make all

    - name: Test
      run: make test

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Publish coverage.html as an artifact
      uses: actions/upload-artifact@master
      with:
        name: coverage
        path: artifacts/coverage.html
